### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by igorgue** [halogenandtoast/monban#34]
Hi,

I'd like to add permissions to my app that's using Monban, I wonder if anybody has experience with that? I know devise has CanCan support, any other libraries I should know about before I just build my own from scratch?

Unfortunately I inherited this project from you guys and zero work was done on permissions (even though, it's clear our app needs permissions).

The ideal scenario would be to do something like this: http://www.phase2technology.com/blog/authentication-permissions-and-roles-in-rails-with-devise-cancan-and-role-model/

**Comment by derekprior** [comment]
> I'd like to add permissions to my app that's using Monban, I wonder if anybody has experience with that? 

Permissions aren't really related to the functionality provided by Monban, which is concerned with authentication and the requirement that users be authenticated.

> Unfortunately I inherited this project from you guys and zero work was done on permissions (even though, it's clear our app needs permissions).

I can't imagine this attitude is going to bring you the results your after here...

> The ideal scenario would be to do something like this:

So do it. That example contains devise-isms but there is no Devise/CanCan integration. You are meant to layer on home-rolled authorization or a separate library.

**Comment by halogenandtoast** [comment]
I don't see why you couldn't just use CanCan if that's what you wanted. I don't see anything built in to devise to make CanCan integration any easier so I'd imagine it would take about the same amount of work either way. I might be missing something in which case feel free to point me to the integration path. It's unlikely that monban would adopt any form of direct integration, but at the same time I want to make sure it's extensible enough so that it doesn't get in the way, so if you have any problems in regards to that I would love to know in order to make it easier. As an aside I played around with a permissions framework but it never really came to fruition.

**Comment by igorgue** [comment]
Yeah, now reading about it, it looks like the only thing I need is the "current_user" method in the controllers and Monban already has that, I'll give it a shot today.

Thanks you for your help guys!
