### ISSUE TITLE
Logout link doesn't work

### ISSUE THREAD

**Issue by suhasg** [halogenandtoast/monban#48]
Logout link takes method as `GET` only when nested under `<li>` tag and not the explicitly mentioned method `DELETE`. 

```
<li>
   <%= link_to(session_path, method: :delete) do %>
       <i class="fa fa-sign-out"></i>
       <%= t("sign_out") %>
   <% end %>
</li>
```

Note: `jquery-rails` gem has been included in gemfile.

**Comment by halogenandtoast** [comment]
@suhasg 

Can you provide the following information:

- Rails version
- Monban version
- jquery-rails version
- Relevant log file output.

Thanks.

**Comment by halogenandtoast** [comment]
@suhasg ,
I have a feeling that this has nothing to do with Monban (since it has no control over which type of request is made). My guesses are that you have an unclosed `<a>` or `<form>` tag somewhere or that your JavaScript is throwing an exception and preventing the `method: :delete` from working correctly.

**Comment by halogenandtoast** [comment]
Closing this due to lack of feedback and that it probably isn't a monban issue.
